#!/bin/python

import urllib.request, json, time, socket

zip_code = "44240,fr"
api_key = "3c342502e41882a24db52edbbd1f329d"
units = "metric"
unit_key = "C"

try:
    host = socket.gethostbyname("www.google.com")
    s = socket.create_connection((host, 80), 2)
except:
    time.sleep(10)
try:
	weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?zip={}&APPID={}&units={}".format(zip_code, api_key, units)).read())[2:-1])
	info = weather["weather"][0]["description"].capitalize()
	temp = int(float(weather["main"]["temp"]))
	if info == "Clear sky":
	    print(" %i°%s" % (temp, unit_key))
	elif temp > 0:
	    print(" %i°%s" % (temp, unit_key))
except:
	exit(1)
